/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BabTyping {
    'classes': string;
    'duration': number;
    'effect': string;
    'reset': () => void;
    'text': string;
  }
  interface BabTypingAttributes extends StencilHTMLAttributes {
    'classes'?: string;
    'duration'?: number;
    'effect'?: string;
    'onTypingFinish'?: (event: CustomEvent) => void;
    'onTypingStart'?: (event: CustomEvent) => void;
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BabTyping': Components.BabTyping;
  }

  interface StencilIntrinsicElements {
    'bab-typing': Components.BabTypingAttributes;
  }


  interface HTMLBabTypingElement extends Components.BabTyping, HTMLStencilElement {}
  var HTMLBabTypingElement: {
    prototype: HTMLBabTypingElement;
    new (): HTMLBabTypingElement;
  };

  interface HTMLElementTagNameMap {
    'bab-typing': HTMLBabTypingElement
  }

  interface ElementTagNameMap {
    'bab-typing': HTMLBabTypingElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
